# Generated by Django 6.0.3 on 2026-03-19 07:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('CASTE', 'Caste Certificate'), ('INCOME', 'Income Certificate'), ('BIRTH', 'Birth Certificate'), ('DEATH', 'Death Certificate')], max_length=20)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ASSIGNED', 'Assigned'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('OVERDUE', 'Overdue')], default='SUBMITTED', max_length=15)),
                ('applicant_name', models.CharField(max_length=100)),
                ('applicant_dob', models.DateField()),
                ('applicant_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('applicant_phone', models.CharField(max_length=15)),
                ('applicant_address', models.TextField()),
                ('aadhar_number', models.CharField(max_length=12)),
                ('aadhar_photo', models.ImageField(blank=True, null=True, upload_to='aadhar/%Y/%m/')),
                ('caste_name', models.CharField(blank=True, max_length=100)),
                ('caste_category', models.CharField(blank=True, choices=[('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('General', 'General')], max_length=10)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('purpose', models.TextField(blank=True)),
                ('annual_income', models.CharField(blank=True, max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('income_purpose', models.TextField(blank=True)),
                ('birth_place', models.CharField(blank=True, max_length=200)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('birth_father_name', models.CharField(blank=True, max_length=100)),
                ('hospital_name', models.CharField(blank=True, max_length=200)),
                ('deceased_name', models.CharField(blank=True, max_length=100)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('death_place', models.CharField(blank=True, max_length=200)),
                ('cause_of_death', models.CharField(blank=True, max_length=200)),
                ('informant_name', models.CharField(blank=True, max_length=100)),
                ('relation_to_deceased', models.CharField(blank=True, max_length=50)),
                ('submitted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to='users.officerprofile')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_date'],
            },
        ),
    ]
